/*
 * Library Management System - Ayas Nasih, S1600655
 * 
 * 
 */
package villalibraryms.Forms;

import villalibraryms.Repositories.BookRepository;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import villalibraryms.VillaLibraryMS;
import villalibraryms.VillaLibraryMS.SessionData;

/**
 *
 * @author ayasnasih
 */
public class FindBooks extends javax.swing.JFrame {

    /**
     * Creates new form FindBooks
     */
    public FindBooks() {
        initComponents();
        btnSearch.doClick();
        if(!SessionData.currentUser.getRole().name.equals("admin")) {
            btnDelete.setEnabled(false);
        }
    }

    private enum SearchMode {
        TITLE,
        AUTHOR,
        SUBJECT,
        PUB_YEAR
    }

    private SearchMode searchMode = SearchMode.TITLE;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        rdTitle = new javax.swing.JRadioButton();
        rdAuthor = new javax.swing.JRadioButton();
        rdSubject = new javax.swing.JRadioButton();
        rdPubYear = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Books");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Search Terms");

        btnDelete.setText("Delete Selected Book");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdTitle);
        rdTitle.setSelected(true);
        rdTitle.setText("Title");
        rdTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTitleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdAuthor);
        rdAuthor.setText("Author");
        rdAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAuthorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdSubject);
        rdSubject.setText("Subject");
        rdSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSubjectActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPubYear);
        rdPubYear.setText("Publication Year");
        rdPubYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPubYearActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete1.setText("Reserve This Book");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addGap(25, 25, 25)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdTitle)
                                .addGap(18, 18, 18)
                                .addComponent(rdAuthor)
                                .addGap(18, 18, 18)
                                .addComponent(rdSubject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdPubYear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdTitle)
                            .addComponent(rdAuthor)
                            .addComponent(rdSubject)
                            .addComponent(rdPubYear)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        int bookId = Integer.parseInt((String) jTable1.getValueAt(selectedRow, 1).toString());
        BookRepository.deleteBook(bookId);
        btnSearch.doClick();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rdAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAuthorActionPerformed
        // TODO add your handling code here:
        if (rdAuthor.isSelected()) {
            searchMode = searchMode.AUTHOR;
        }
    }//GEN-LAST:event_rdAuthorActionPerformed

    private void rdTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTitleActionPerformed
        // TODO add your handling code here:
        if (rdTitle.isSelected()) {
            searchMode = searchMode.TITLE;
        }
    }//GEN-LAST:event_rdTitleActionPerformed

    private void rdSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSubjectActionPerformed
        // TODO add your handling code here:
        if (rdSubject.isSelected()) {
            searchMode = searchMode.SUBJECT;
        }
    }//GEN-LAST:event_rdSubjectActionPerformed

    private void rdPubYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPubYearActionPerformed
        // TODO add your handling code here:
        if (rdPubYear.isSelected()) {
            searchMode = searchMode.PUB_YEAR;
        }
    }//GEN-LAST:event_rdPubYearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchString = jTextField1.getText();
        ResultSet rs;
        switch (searchMode) {
            default:
            case TITLE:
                rs = BookRepository.findBookBy("title", searchString);
                break;
            case AUTHOR:
                rs = BookRepository.findBookByAuthor(searchString);
                break;
            case SUBJECT:
                rs = BookRepository.findBookBySubject(searchString);
                break;
            case PUB_YEAR:
                rs = BookRepository.findBookBy("publication_year", searchString);
                break;
        }
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        int bookItemId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        int bookId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        int availableCopies = BookRepository.availableCopies(bookId);
        System.out.println(availableCopies);
        if(BookRepository.reservationExists(bookItemId, Integer.parseInt(SessionData.Uid))) {
            JOptionPane.showMessageDialog(null, "You've already reserved this book");
            return;
        }
        if (availableCopies > 0) {
            JOptionPane.showMessageDialog(null, "Cannot reserve while there are available copies!");
        } else {

            BookRepository.reserveBook(bookItemId, Integer.parseInt(SessionData.Uid));
            JOptionPane.showMessageDialog(null, "Reserved!");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdAuthor;
    private javax.swing.JRadioButton rdPubYear;
    private javax.swing.JRadioButton rdSubject;
    private javax.swing.JRadioButton rdTitle;
    // End of variables declaration//GEN-END:variables
}
