/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package villalibraryms;

import villalibraryms.Util.SqlStatements;
import villalibraryms.Util.DBUtils;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author ayasnasih
 */
public class UserMenu extends javax.swing.JFrame {

    /**
     * Creates new form UserMenu
     */
    private DBUtils db = DBUtils.getInstance();
    private Connection connection = db.getConnection();

    public UserMenu() {
        initComponents();
        jLabel1.setText(jLabel1.getText().replace("{user}", VillaLibraryMS.SessionData.loggedInUsername));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewBooks = new javax.swing.JButton();
        btnMyBooks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Dashboard");
        setResizable(false);

        btnViewBooks.setText("View Books");
        btnViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBooksActionPerformed(evt);
            }
        });

        btnMyBooks.setText("My Books");
        btnMyBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyBooksActionPerformed(evt);
            }
        });

        jLabel1.setText("Hello {user}! Welcome to your dashboard.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnMyBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyBooks)
                    .addComponent(btnViewBooks))
                .addGap(124, 124, 124))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBooksActionPerformed
        JFrame f = new JFrame("Books Available"); //View books stored in database
        try {
            Statement stmt = connection.createStatement(); //connect to database
            ResultSet rs = stmt.executeQuery(SqlStatements.ALL_BOOKS);
            JTable book_list = new JTable(); //show data in table format
            book_list.setModel(DbUtils.resultSetToTableModel(rs));

            JScrollPane scrollPane = new JScrollPane(book_list); //enable scroll bar

            f.add(scrollPane); //add scroll bar
            f.setSize(800, 400); //set dimensions of view books frame
            f.setVisible(true);
            f.setLocationRelativeTo(null);
        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e1);
        }
    }//GEN-LAST:event_btnViewBooksActionPerformed

    private void btnMyBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyBooksActionPerformed

        JFrame f = new JFrame("My Books"); //View books issued by user
        int UID_int = Integer.parseInt(VillaLibraryMS.SessionData.Uid); //Pass user ID

        //.iid,issued.uid,issued.bid,issued.issued_date,issued.return_date,issued,
        //retrieve data
        String sql = "select distinct issued.*,books.bname,books.genre,books.price from issued,books " + "where ((issued.uid=" + UID_int + ") and (books.bid in (select bid from issued where issued.uid=" + UID_int + "))) group by iid";
        String sql1 = "select bid from issued where uid=" + UID_int;
        try {
            Statement stmt = connection.createStatement();
            //store in array
            ArrayList books_list = new ArrayList();

            ResultSet rs = stmt.executeQuery(sql);
            JTable book_list = new JTable(); //store data in table format
            book_list.setModel(DbUtils.resultSetToTableModel(rs));
            //enable scroll bar
            JScrollPane scrollPane = new JScrollPane(book_list);

            f.add(scrollPane); //add scroll bar
            f.setSize(800, 400); //set dimensions of my books frame
            f.setVisible(true);
            f.setLocationRelativeTo(null);
        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e1);
        }

    }//GEN-LAST:event_btnMyBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMyBooks;
    private javax.swing.JButton btnViewBooks;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
